sudo: required
services:
    - docker

before_install:
    - gem install bundler
    - docker build -t keso93/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true keso93/docker-react npm run test